import pandas as pd, numpy as np, json
D=pd.read_pickle('delivery.pkl'); T=pd.read_pickle('tables.pkl'); P=pd.read_pickle('permitted.pkl')
R=pd.Timestamp('2026-09-29')
D['sector']=np.where(D.owner.str.startswith('Public'),'Public','Private'); P['sector']=np.where(P.owner.str.startswith('Public'),'Public','Private')
f={}
n=lambda x: f'{int(round(x)):,}'
d1=lambda x: f'{x:.1f}'
pc=lambda x: f'{int(round(x))}%'
f['schemes']=n(len(D)); f['permitted']=n(len(P)); f['units_permitted']=n(P.units.sum())
su=P.groupby('status4').units.sum()
f['u_complete']=n(su['Complete']); f['u_uc']=n(su['Under construction']); f['u_ns_live']=n(su['Not started – permission live']); f['u_ns_past']=n(su['Not started – past expiry'])
f['u_ns']=n(su['Not started – permission live']+su['Not started – past expiry'])
f['approval_med']=d1(D.approval_yrs.median()); f['approval_months']=n(D.approval_yrs.median()*12)
reg=D[D.route.isin(['Standard planning application','LRD'])]
nf=reg[~reg.fi&~reg.appealed]; f['nofi_weeks']=n(nf.approval_yrs.median()*52.18); f['nofi_med']=d1(nf.approval_yrs.median())
f['fi_med']=d1(reg[reg.fi&~reg.appealed].approval_yrs.median()); f['appeal_med']=d1(reg[reg.appealed].approval_yrs.median())
f['fi_share']=pc(100*reg.fi.mean())
f['g2s_med']=d1(D.grant_to_start_yrs.median()); f['g2s_n']=n(D.grant_to_start_yrs.notna().sum())
t3=T['3 Share started over time'].set_index('Scheme size')
for k in [1,2,3,5]: f[f'st{k}']=pc(t3.loc['All',f'Started within {k} yr (%)'])
f['st5_small']=pc(t3.loc['1–24 units','Started within 5 yr (%)']); f['st5_mid']=pc(t3.loc['25–99 units','Started within 5 yr (%)'])
c=D[D.stage=='Complete']; e=(c.completion-c.received).dt.days/365.25
f['e2e_med']=d1(e.median()); f['e2e_lq']=d1(e.quantile(.25)); f['e2e_uq']=d1(e.quantile(.75)); f['n_complete']=n(len(c))
f['build_med']=d1(D.start_to_complete_yrs.median())
t9=T['9 Build rates'].set_index('Group'); f['dpa_small']=n(t9.loc['1–9','Median build rate (dpa)']); f['dpa_large']=n(t9.loc['100+','Median build rate (dpa)'])
t6=T['6 Expiry of unstarted'].set_index('Expiry window')['Total units']
f['exp_past']=n(t6['Already past expiry']); f['exp_12']=n(t6['Within 12 months']); f['exp_24']=n(t6['12–24 months']); f['exp_36']=n(t6['24–36 months']); f['exp_more']=n(t6['More than 36 months']); f['exp_none']=n(t6['No expiry date (mainly Part 8)'])
f['exp_2yr']=n(t6['Within 12 months']+t6['12–24 months']); f['exp_risk']=n(t6['Already past expiry']+t6['Within 12 months']+t6['12–24 months'])
ns=P[P.status4.str.startswith('Not started')]; f['ns_recent']=n(ns[ns.final_grant>R-pd.DateOffset(years=2)].units.sum())
coh=P[P.final_grant<=R-pd.DateOffset(years=2)]; st=coh.status4.isin(['Complete','Under construction'])
f['coh_n']=n(len(coh)); f['coh_units']=n(coh.units.sum()); f['coh_pct']=pc(100*coh.loc[st,'units'].sum()/coh.units.sum())
L=T['4a Implementation by LEA'].set_index('lea')
for k,v in {'east':'Limerick City East','north':'Limerick City North','west':'Limerick City West','ar':'Adare-Rathkeale','ck':'Cappamore-Kilmallock','nw':'Newcastle West'}.items():
    f[f'lea_{k}']=pc(L.loc[v,'Units started (%)']); f[f'lea_{k}_g2s']=d1(L.loc[v,'Median grant to start (yrs)'])
f['ar_started']=n(L.loc['Adare-Rathkeale','Units started']); f['ar_units']=n(L.loc['Adare-Rathkeale','Units permitted'])
f['nw_started']=n(L.loc['Newcastle West','Units started']); f['nw_units']=n(L.loc['Newcastle West','Units permitted'])
rt=T['4d Implementation by route'].set_index('route')
f['shd_units']=n(rt.loc['SHD (An Bord Pleanála)','Units permitted']); f['shd_started']=n(rt.loc['SHD (An Bord Pleanála)','Schemes started']); f['shd_pct']=pc(rt.loc['SHD (An Bord Pleanála)','Units started (%)'])
f['std_pct']=pc(rt.loc['Standard planning application','Units started (%)'])
f['p8_pct']=pc(rt.loc['Part 8 / council','Units started (%)']); f['p8_coh']=n(rt.loc['Part 8 / council','Schemes'])
f['p8_total']=n((D.route=='Part 8 / council').sum()); f['p8_added']=n((D.source!='CIS').sum()); f['p8_added_units']=n(D.loc[D.source!='CIS','units'].sum())
f['p8_matched']=n(((D.register_ref!=D.ref)&(D.source=='CIS')).sum())
f['pub_n']=n((D.sector=='Public').sum()); f['pub_units']=n(D.loc[D.sector=='Public','units'].sum()); f['pub_share']=pc(100*D.loc[D.sector=='Public','units'].sum()/D.units.sum())
o=D.groupby('owner').agg(k=('units','size'),u=('units','sum'))
f['la_n']=n(o.loc['Public – local authority','k']); f['la_u']=n(o.loc['Public – local authority','u']); f['ahb_n']=n(o.loc['Public – approved housing body','k']); f['ahb_u']=n(o.loc['Public – approved housing body','u'])
t3b=T['3b Started over time by sector'].set_index('Sector')
for s_ in ['Public','Private']:
    for k in [2,5]: f[f'{s_[:3].lower()}_st{k}']=pc(t3b.loc[s_,f'Started within {k} yr (%)'])
tb=T['2b Timeline by sector'].set_index('Sector')
f['pub_g2s']=d1(tb.loc['Public','Grant to start: median']); f['pri_g2s']=d1(tb.loc['Private','Grant to start: median'])
f['pub_appr']=d1(tb.loc['Public','Approval: median']); f['pri_appr']=d1(tb.loc['Private','Approval: median'])
sc=T['4g Implementation by sector'].set_index('sector'); f['pub_coh_pct']=pc(sc.loc['Public','Units started (%)']); f['pri_coh_pct']=pc(sc.loc['Private','Units started (%)'])
t12=T['12 Status by nbhd'].set_index('Neighbourhood'); city=t12.drop('Outside city neighbourhoods')
f['city_units']=n(city['Total units'].sum()); f['city_share']=pc(100*city['Total units'].sum()/t12['Total units'].sum())
f['city_schemes']=n(city.Schemes.sum())
top=city['Total units'].sort_values(ascending=False); f['nb_top1']=top.index[0]; f['nb_top1_u']=n(top.iloc[0]); f['nb_top2']=top.index[1]; f['nb_top2_u']=n(top.iloc[1]); f['nb_top3']=top.index[2]; f['nb_top3_u']=n(top.iloc[2])
nb=T['4h Implementation by nbhd'].set_index('nbhd')
for k,v in {'cc':'City Centre','ct':'Castletroy/Annacotty','sh':'Southhill','dd':'Dooradoyle','cd':'Caherdavin','bc':'Ballinacurra','sg':'Singland/Garryowen'}.items():
    f[f'nb_{k}']=pc(nb.loc[v,'Units started (%)']); f[f'nb_{k}_u']=n(nb.loc[v,'Units permitted'])
f['cc_pub_share']=pc(t12.loc['City Centre','Public share (%)']); f['cc_ns']=n(t12.loc['City Centre','Not started – permission live']+t12.loc['City Centre','Not started – past expiry']); f['cc_total']=n(t12.loc['City Centre','Total units'])
f['ct_ns']=n(t12.loc['Castletroy/Annacotty','Not started – permission live']); f['dd_ns']=n(t12.loc['Dooradoyle','Not started – permission live'])
t8=T['8 Annual flows'].set_index('Year'); f['granted_2026']=n(t8.loc[2026,'Units granted']); f['start_peak_year']=str(t8['Units started'].idxmax()); f['start_peak']=n(t8['Units started'].max())
b=T['10 Barrier indicators'].set_index('Indicator')
f['onhold']=n(b.loc['Schemes with CIS note: on hold / no movement','Schemes / applications']); f['fi_schemes']=n(b.loc['Schemes where further information was requested','Schemes / applications'])
f['ccc_units']=n(c.ccc_units.sum()); f['cis_units']=n(c.units.sum()); f['ccc_n']=n((c.ccc_count>0).sum())
ce=ns[ns.lea=='Limerick City East']; f['ce_recent_share']=pc(100*ce[ce.final_grant>=pd.Timestamp('2025-01-01')].units.sum()/ce.units.sum())
f['sh_n']=n((D.sh_no!='').sum()); f['sh_units']=n(D.loc[D.sh_no!='','units'].sum()); f['sh_turnkey']=n((D.sh_mode=='Turnkey').sum()); f['sh_completed']=n((D.completion_source=='Department social housing report').sum())
json.dump(f,open('facts.json','w'),indent=1,ensure_ascii=False)
for k,v in f.items(): print(k,'=',v)
